
TOOLS := ${HOME}/.shortcuts/ChatGPT
TOOLS += ${HOME}/.shortcuts/CarGPT

.PHONY: default
default:
	echo "make install"

${HOME}/.shortcuts:
	mkdir "$@"

${HOME}/.shortcuts/ChatGPT: | ${HOME}/.shortcuts
	cp termux_android_shortcuts/chatgpt.sh "$@"

${HOME}/.shortcuts/CarGPT: | ${HOME}/.shortcuts
	cp termux_android_shortcuts/cargpt.sh "$@"

.PHONY: install
install: ${TOOLS}
	$(MAKE) -f Makefile "$@"
